### ISSUE TITLE
Requires selection to perform lookup

### ISSUE THREAD

**Issue by rchl** [tushortz/LangDocs#4]
Triggering the plugin (at least in CSS or HTML) without making a selection triggers lookup with an empty string, I believe. This is quite useless - it will probably never return an useful result.

The plugin could be made smarter by looking up the word under the cursor when no selection was made. The pattern for word matching could be something like [a-z-_] or something similar. Maybe the pattern should be different depending on the syntax. That would require some investigation what is the best approach.

**Comment by tushortz** [comment]
Thanks once again for these suggestions but I guess I need to Learn more of
sublime text to implement these features

**Comment by tushortz** [comment]
I did a similar thing for just selecting class name before but for some reason, I had to remove it because Java has classes with similar names in different packages. e.g. `InputStream` and had to change to remove duplicates and invalid lookups.

I'm sure there are better ways but that would require extra research
